services:
  - type: web
    name: flask-pushup-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -k eventlet -w 1 pushup:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-flask-db
          property: connectionString

databases:
  - name: my-flask-db
    plan: free
